/* About & privacy — states the privacy position plainly, credits open
   resources, and is honest about machine-authored translations. */
import { Modal } from './Modal.jsx';
import { AacashWordmark } from './Logo.jsx';

export function About({ onClose }) {
  return (
    <Modal title="About AACASH" onClose={onClose}>
      <div style={{ marginBottom: 'var(--sp-4)' }}>
        <AacashWordmark markSize={52} />
      </div>
      <p style={{ marginBottom: 'var(--sp-3)', lineHeight: 1.6 }}>
        <b>AACASH</b> — Augmentative and Alternative Communication · Autism Spectrum Helper — is a free
        communication board for children and non-speaking people in India. Tap symbols to build sentences and
        speak them aloud in English, Tamil, Hindi, Telugu, Bengali, Marathi, or Kannada.
      </p>

      <h3 style={{ color: 'var(--ac-primary)', margin: 'var(--sp-4) 0 var(--sp-2)' }}>Privacy</h3>
      <p style={{ lineHeight: 1.6 }}>
        Everything stays on this device. Profiles, photos, recordings, and usage history are stored locally in your
        browser (localStorage and IndexedDB). AACASH has <b>no accounts, no analytics, no tracking, and makes no
        network requests with your child’s data</b>. Backups are files you create and keep yourself. Speech is
        generated by your device’s own voices; on some browsers (e.g. Chrome with online voices) the text of a
        spoken word may be processed by the browser’s speech service — install offline voices to avoid this.
      </p>

      <h3 style={{ color: 'var(--ac-primary)', margin: 'var(--sp-4) 0 var(--sp-2)' }}>Prediction</h3>
      <p style={{ lineHeight: 1.6 }}>
        Word and phrase suggestions come from an on-device model that learns this child’s own usage — by hour of
        day and weekday/weekend — on top of common AAC sentence patterns. The learning never leaves the device.
      </p>

      <h3 style={{ color: 'var(--ac-primary)', margin: 'var(--sp-4) 0 var(--sp-2)' }}>AAC principles</h3>
      <ul style={{ lineHeight: 1.7, paddingLeft: '1.2em', margin: 0 }}>
        <li>Core words are always visible and <b>never move</b> (motor planning).</li>
        <li>Fitzgerald Key colour coding by part of speech.</li>
        <li>Symbol + text on every button; row–column switch scanning; large touch targets.</li>
        <li>No timeouts, nothing auto-dismisses, motion can be reduced.</li>
      </ul>

      <h3 style={{ color: 'var(--ac-primary)', margin: 'var(--sp-4) 0 var(--sp-2)' }}>Translations</h3>
      <p style={{ lineHeight: 1.6 }}>
        Board words and phrases were written with care but have <b>not all been reviewed by native speakers</b>.
        Please have a fluent speaker check your language — especially the emergency phrases — before relying on
        them. Corrections are welcome.
      </p>

      <h3 style={{ color: 'var(--ac-primary)', margin: 'var(--sp-4) 0 var(--sp-2)' }}>Credits</h3>
      <p style={{ lineHeight: 1.6 }}>
        Symbols: <a href="https://openmoji.org" target="_blank" rel="noreferrer">OpenMoji</a> (CC BY-SA 4.0).
        Type: Inter (Rasmus Andersson) and Noto Sans (Google), both SIL Open Font License. AACASH is not a medical
        device and does not replace guidance from a speech-language pathologist.
      </p>
    </Modal>
  );
}
